

align-items: center;
background-color: rgb(157, 0, 56);
border-bottom-color: rgb(255, 255, 255);
border-bottom-left-radius: 50%;
border-bottom-right-radius: 50%;
border-bottom-style: none;
border-bottom-width: 0px;
border-image-outset: 0;
border-image-repeat: stretch;
border-image-slice: 100%;
border-image-source: none;
border-image-width: 1;
border-left-color: rgb(255, 255, 255);
border-left-style: none;
border-left-width: 0px;
border-right-color: rgb(255, 255, 255);
border-right-style: none;
border-right-width: 0px;
border-top-color: rgb(255, 255, 255);
border-top-left-radius: 50%;
border-top-right-radius: 50%;
border-top-style: none;
border-top-width: 0px;
box-shadow: rgba(0, 0, 0, 0.2) 0px 3px 5px -1px, rgba(0, 0, 0, 0.14) 0px 6px 10px 0px, rgba(0, 0, 0, 0.12) 0px 1px 18px 0px;
box-sizing: border-box;
color: rgb(255, 255, 255);
cursor: pointer;
display: inline-flex;
font-family: "Roboto", "Helvetica", "Arial", sans-serif;
font-size: 14px;
font-weight: 500;
height: 40px;
justify-content: center;
letter-spacing: 0.4px;
line-height: 24.5px;
margin-bottom: 8px;
margin-left: 8px;
margin-right: 8px;
margin-top: 8px;
min-height: 36px;
min-width: 0px;
outline-color: rgb(255, 255, 255);
outline-style: none;
outline-width: 0px;
padding-bottom: 0px;
padding-left: 0px;
padding-right: 0px;
padding-top: 0px;
position: relative;
text-decoration: none;
text-decoration-color: rgb(255, 255, 255);
text-decoration-line: none;
text-decoration-style: solid;
text-transform: uppercase;
transition-delay: 0s, 0s, 0s;
transition-duration: 0.25s, 0.25s, 0.25s;
transition-property: background-color, box-shadow, border;
transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1), cubic-bezier(0.4, 0, 0.2, 1), cubic-bezier(0.4, 0, 0.2, 1);
vertical-align: middle;
width: 40px;
-moz-appearance: none;
-moz-user-select: none;